name: ci

on: [push, pull_request]

jobs:
    test:
        name: ${{ matrix.config.display-name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                config:
                    - {
                          display-name: "test (cpu)",
                          docker-file: "Dockerfile",
                          image-slug: "facefusion/facefusion:${{ github.ref_name }}-cpu",
                      }
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: docker build -f ${{ matrix.config.docker-file }} -t ${{ matrix.config.image-slug }} .
            - name: Run
              run: docker run -d ${{ matrix.config.image-slug }}
            - name: Validate
              run: docker ps | grep -q ${{ matrix.config.image-slug }}
    deploy:
        name: ${{ matrix.config.display-name }}
        runs-on: ubuntu-latest
        needs: test
        strategy:
            matrix:
                config:
                    - {
                          display-name: "deploy (cpu)",
                          docker-file: "Dockerfile",
                          image-slug: "facefusion/facefusion:${{ github.ref_name }}-cpu",
                      }
        steps:
            - name: Login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: docker build -f ${{ matrix.config.docker-file }} -t ${{ matrix.config.image-slug }} .
            - name: Deploy
              run: docker push ${{ matrix.config.image-slug }}
            - name: Logout
              run: docker logout
