name: ci

on: [push, pull_request]

jobs:
    deploy:
        name: ${{ matrix.config.display-name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                config:
                    - {
                          display-name: "deploy (cpu)",
                          docker-file: "Dockerfile",
                          image-slug: "ghcr.io/leslie-luo/facefusion:${{ github.ref_name }}-cpu",
                      }
        steps:
            - name: Login
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: docker build -f ${{ matrix.config.docker-file }} -t ${{ matrix.config.image-slug }} .
            - name: Deploy
              run: docker push ${{ matrix.config.image-slug }}
            - name: Logout
              run: docker logout
